<a href="https://colab.research.google.com/github/svetlanama/math/blob/main/Home_work_1_Template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Нагадування по Markdown

Надаємо невелике нагадування записів в
[Markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb) (LaTeX):

Markdown | Preview
--- | ---
`**bold text**` | **bold text**
 \\$\frac{x}{y}\\$ | $\frac{x}{y}$
 \\$p^{x}_{y}\\$ | $p^{x}_{y}$
\\$x \cdot y\\$ | $x \cdot y$
\\$\sqrt{x}\\$ | $\sqrt{x}$
\\$\pi\\$ | $\pi$
\\$\approx\\$ | $\approx$

І ще декілька прикладів:

```markdown
$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

 $$
 I =
 \left (\begin{array}{cc}
 1 & 0\\
 0 & 1
 \end{array}\right)
 $$
```

$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

$I =
\left (\begin{array}{cc}
1 & 0\\
0 & 1
\end{array}\right)$
 ---

# Завдання 1.
В шаблоні наведені числові вектори $\overline{a}$ та $\overline{b}$. Порахуй наступне:
- сума $\overline{a}$ та $\overline{b}$
- різниця $\overline{a}$ та $\overline{b}$
- сума $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}^T$.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- добуток Адамара (Hadamard product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.

In [ ]:
import numpy as np
# Код оголошення векторів не можна змінювати
a = np.array([[1, 2, 3, 4, 5]])
b = np.array([[1/2, 1, 2, 3, 4]])

In [ ]:
res = "Встав код"
res = a + b
res

array([[1.5, 3. , 5. , 7. , 9. ]])

In [ ]:
res = "Встав код"
res = a - b
res

array([[0.5, 1. , 1. , 1. , 1. ]])

# Пояснення:

\
a =
\begin{bmatrix}
1 & 2 & 3 & 4 & 5
\end{bmatrix}
size = 1 x 5

___________________________________
\
b^T =
\begin{bmatrix}
0.5 \\
1 \\
2 \\
3 \\
4
\end{bmatrix}
size = 5 x 1
___________________________________

\
a + b^T =
\begin{bmatrix}
1.5 & 2.5 & 3.5 & 4.5 & 5.5 \\
2.0 & 3.0 & 4.0 & 5.0 & 6.0 \\
3.0 & 4.0 & 5.0 & 6.0 & 7.0 \\
4.0 & 5.0 & 6.0 & 7.0 & 8.0 \\
5.0 & 6.0 & 7.0 & 8.0 & 9.0
\end{bmatrix}

___________________________________
Поясненя
- Копіює a по вертикалі, щоб у нього стало 5 рядків.  
- Копіює b^T по горизонталі, щоб стало 5 стовпців.  
- У результаті утворюється матриця розміром 5×5.  

Кожен елемент (i,j) обчислюється так:  
результат[i,j] = a[j] + b[i]


In [25]:
# Пояснення:
# отримаємо транспоноване  b_T, де рядки замінюються на стовпці
# тобто b вектор був розміром 1x5 , b_T = 5x1

res = "Встав код"
b_T = b.T
print("shape: ",b_T.shape)
result = a + b_T

print("b^T:\n", b_T)
print("\nРезультат a + b^T:\n", result)
print("shape: ",result.shape)

shape:  (5, 1)
b^T:
 [[0.5]
 [1. ]
 [2. ]
 [3. ]
 [4. ]]

Результат a + b^T:
 [[1.5 2.5 3.5 4.5 5.5]
 [2.  3.  4.  5.  6. ]
 [3.  4.  5.  6.  7. ]
 [4.  5.  6.  7.  8. ]
 [5.  6.  7.  8.  9. ]]
shape:  (5, 5)


In [ ]:

res = "Встав код"
res = a +

In [ ]:
# Пояснення:
res = "Встав код"
res

In [ ]:
# Пояснення:
res = "Встав код"
res

In [ ]:
# Пояснення:
res = "Встав код"
res

In [ ]:
# Пояснення:
res = "Встав код"
res

# Завдання 2
В цьому завданні ти навчишся перетворювати вектори за допомогою афінних перетворень.  
Дано вектор:
$$
x =
\left(\begin{array}{cc}
2\\
1
\end{array}\right)
$$


Виконай аналітично наступні завдання задавши матрицю перетворення та застосуй її до вектора $x$:

1. Зменши вектор $x$ в 2 рази по вісі $OX$ та збільш в 3 рази по вісі $OY$.
2. Відобрази вектор $x$ відносно початку координат.
3. Перенеси вектор $x$ на -3 по вісі $OX$ та на 1 по вісі $OY$.
4. Змісти вектор $x$ на 60° по вісі $OY$.
5. Поверни вектор $x$ на 30°.
6. Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$.

#### 2.1 Зменши вектор  $x$  в 2 рази по вісі  OX  та збільш в 3 рази по вісі  OY .

$$
M_1 =
\left (\begin{array}{cc}
? & ?\\
? & ?\\
\end{array}\right)
$$

$$
M_1x =
\left(\begin{array}{cc}
? & ?\\
? & ?
\end{array}\right)
\left (\begin{array}{cc}
2\\
1
\end{array}\right)=
\left(\begin{array}{cc}
? \cdot 2 + ? \cdot 1\\
? \cdot 2 + ? \cdot 1
\end{array}\right)=
\left(\begin{array}{cc}
?\\
?
\end{array}\right)
$$

#### 2.2 Відобрази вектор $x$ відносно початку координат.

$$
M_2 = ?
\\
M_2x = ?
$$

#### 2.3 Перенеси вектор $x$, задавши відповідну матрицю і помноживши на неї,  на -3 по вісі $OX$ та на 1 по вісі $OY$.

$$
M_3 = ?
\\
M_3x = ?
$$

#### 2.4 Змісти(shear) вектор $x$ на 60° по вісі $OY$.


$$
M_4 = ?
\\
M_4x = ?
$$

#### 2.5 Поверни вектор $x$ на 30°.

$$
M_5 = ?
\\
M_5x = ?
$$

#### 2.6 Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$.

$$
M_6 = M_5 \cdot M_4 \cdot M_2 \cdot M_1 = ?
$$

$$
M_6 =
\left (\begin{array}{cc}
? & ?\\
? & ?
\end{array}\right)
\\
M_6x = ?
$$

# Завдання 2 (Альтернативне)

In [ ]:
import cv2 as cv
import urllib
import numpy as np
from google.colab.patches import cv2_imshow as cv_imshow

# Read an image
def read_image_by_url(url):
    req = urllib.request.urlopen(url)
    arr = np.asarray(bytearray(req.read()), dtype=np.uint8)
    img = cv.imdecode(arr, -1)
    return img

url = ''

img = read_image_by_url(url)

In [ ]:
cv_imshow(img)